"""us/watchlist.py — S&P 500 constituents (US bot).

STATIC SNAPSHOT. Snapshot date fixed by build: 2026-06-28.
Source: https://raw.githubusercontent.com/datasets/s-and-p-500-companies/main/data/constituents.csv
# refresh: re-run constituents fetch (replace SP500 literal below with the new list).

Contract (relied on by all other us/ scripts):
  SP500          list of {'yf', 'name', 'sector'} dicts
  STOCKS         [(yf, name), ...]
  YF_TO_NAME     {yf: name}
  YF_TO_SECTOR   {yf: sector}
yf symbols are normalized for yfinance: '.' -> '-' (e.g. BRK.B -> BRK-B, BF.B -> BF-B).
"""

SP500 = [
    {'yf': 'MMM', 'name': '3M', 'sector': 'Industrials'},
    {'yf': 'AOS', 'name': 'A. O. Smith', 'sector': 'Industrials'},
    {'yf': 'ABT', 'name': 'Abbott Laboratories', 'sector': 'Health Care'},
    {'yf': 'ABBV', 'name': 'AbbVie', 'sector': 'Health Care'},
    {'yf': 'ACN', 'name': 'Accenture', 'sector': 'Information Technology'},
    {'yf': 'ADBE', 'name': 'Adobe Inc.', 'sector': 'Information Technology'},
    {'yf': 'AMD', 'name': 'Advanced Micro Devices', 'sector': 'Information Technology'},
    {'yf': 'AES', 'name': 'AES Corporation', 'sector': 'Utilities'},
    {'yf': 'AFL', 'name': 'Aflac', 'sector': 'Financials'},
    {'yf': 'A', 'name': 'Agilent Technologies', 'sector': 'Health Care'},
    {'yf': 'APD', 'name': 'Air Products', 'sector': 'Materials'},
    {'yf': 'ABNB', 'name': 'Airbnb', 'sector': 'Consumer Discretionary'},
    {'yf': 'AKAM', 'name': 'Akamai Technologies', 'sector': 'Information Technology'},
    {'yf': 'ALB', 'name': 'Albemarle Corporation', 'sector': 'Materials'},
    {'yf': 'ARE', 'name': 'Alexandria Real Estate Equities', 'sector': 'Real Estate'},
    {'yf': 'ALGN', 'name': 'Align Technology', 'sector': 'Health Care'},
    {'yf': 'ALLE', 'name': 'Allegion', 'sector': 'Industrials'},
    {'yf': 'LNT', 'name': 'Alliant Energy', 'sector': 'Utilities'},
    {'yf': 'ALL', 'name': 'Allstate', 'sector': 'Financials'},
    {'yf': 'GOOGL', 'name': 'Alphabet Inc. (Class A)', 'sector': 'Communication Services'},
    {'yf': 'GOOG', 'name': 'Alphabet Inc. (Class C)', 'sector': 'Communication Services'},
    {'yf': 'MO', 'name': 'Altria', 'sector': 'Consumer Staples'},
    {'yf': 'AMZN', 'name': 'Amazon', 'sector': 'Consumer Discretionary'},
    {'yf': 'AMCR', 'name': 'Amcor', 'sector': 'Materials'},
    {'yf': 'AEE', 'name': 'Ameren', 'sector': 'Utilities'},
    {'yf': 'AEP', 'name': 'American Electric Power', 'sector': 'Utilities'},
    {'yf': 'AXP', 'name': 'American Express', 'sector': 'Financials'},
    {'yf': 'AIG', 'name': 'American International Group', 'sector': 'Financials'},
    {'yf': 'AMT', 'name': 'American Tower', 'sector': 'Real Estate'},
    {'yf': 'AWK', 'name': 'American Water Works', 'sector': 'Utilities'},
    {'yf': 'AMP', 'name': 'Ameriprise Financial', 'sector': 'Financials'},
    {'yf': 'AME', 'name': 'Ametek', 'sector': 'Industrials'},
    {'yf': 'AMGN', 'name': 'Amgen', 'sector': 'Health Care'},
    {'yf': 'APH', 'name': 'Amphenol', 'sector': 'Information Technology'},
    {'yf': 'ADI', 'name': 'Analog Devices', 'sector': 'Information Technology'},
    {'yf': 'AON', 'name': 'Aon plc', 'sector': 'Financials'},
    {'yf': 'APA', 'name': 'APA Corporation', 'sector': 'Energy'},
    {'yf': 'APO', 'name': 'Apollo Global Management', 'sector': 'Financials'},
    {'yf': 'AAPL', 'name': 'Apple Inc.', 'sector': 'Information Technology'},
    {'yf': 'AMAT', 'name': 'Applied Materials', 'sector': 'Information Technology'},
    {'yf': 'APP', 'name': 'AppLovin', 'sector': 'Information Technology'},
    {'yf': 'APTV', 'name': 'Aptiv', 'sector': 'Consumer Discretionary'},
    {'yf': 'ACGL', 'name': 'Arch Capital Group', 'sector': 'Financials'},
    {'yf': 'ADM', 'name': 'Archer Daniels Midland', 'sector': 'Consumer Staples'},
    {'yf': 'ARES', 'name': 'Ares Management', 'sector': 'Financials'},
    {'yf': 'ANET', 'name': 'Arista Networks', 'sector': 'Information Technology'},
    {'yf': 'AJG', 'name': 'Arthur J. Gallagher & Co.', 'sector': 'Financials'},
    {'yf': 'AIZ', 'name': 'Assurant', 'sector': 'Financials'},
    {'yf': 'T', 'name': 'AT&T', 'sector': 'Communication Services'},
    {'yf': 'ATO', 'name': 'Atmos Energy', 'sector': 'Utilities'},
    {'yf': 'ADSK', 'name': 'Autodesk', 'sector': 'Information Technology'},
    {'yf': 'ADP', 'name': 'Automatic Data Processing', 'sector': 'Industrials'},
    {'yf': 'AZO', 'name': 'AutoZone', 'sector': 'Consumer Discretionary'},
    {'yf': 'AVB', 'name': 'AvalonBay Communities', 'sector': 'Real Estate'},
    {'yf': 'AVY', 'name': 'Avery Dennison', 'sector': 'Materials'},
    {'yf': 'AXON', 'name': 'Axon Enterprise', 'sector': 'Industrials'},
    {'yf': 'BKR', 'name': 'Baker Hughes', 'sector': 'Energy'},
    {'yf': 'BALL', 'name': 'Ball Corporation', 'sector': 'Materials'},
    {'yf': 'BAC', 'name': 'Bank of America', 'sector': 'Financials'},
    {'yf': 'BAX', 'name': 'Baxter International', 'sector': 'Health Care'},
    {'yf': 'BDX', 'name': 'Becton Dickinson', 'sector': 'Health Care'},
    {'yf': 'BRK-B', 'name': 'Berkshire Hathaway', 'sector': 'Financials'},
    {'yf': 'BBY', 'name': 'Best Buy', 'sector': 'Consumer Discretionary'},
    {'yf': 'TECH', 'name': 'Bio-Techne', 'sector': 'Health Care'},
    {'yf': 'BIIB', 'name': 'Biogen', 'sector': 'Health Care'},
    {'yf': 'BLK', 'name': 'BlackRock', 'sector': 'Financials'},
    {'yf': 'BX', 'name': 'Blackstone Inc.', 'sector': 'Financials'},
    {'yf': 'XYZ', 'name': 'Block, Inc.', 'sector': 'Financials'},
    {'yf': 'BNY', 'name': 'BNY Mellon', 'sector': 'Financials'},
    {'yf': 'BA', 'name': 'Boeing', 'sector': 'Industrials'},
    {'yf': 'BKNG', 'name': 'Booking Holdings', 'sector': 'Consumer Discretionary'},
    {'yf': 'BSX', 'name': 'Boston Scientific', 'sector': 'Health Care'},
    {'yf': 'BMY', 'name': 'Bristol Myers Squibb', 'sector': 'Health Care'},
    {'yf': 'AVGO', 'name': 'Broadcom', 'sector': 'Information Technology'},
    {'yf': 'BR', 'name': 'Broadridge Financial Solutions', 'sector': 'Industrials'},
    {'yf': 'BRO', 'name': 'Brown & Brown', 'sector': 'Financials'},
    {'yf': 'BF-B', 'name': 'Brown–Forman', 'sector': 'Consumer Staples'},
    {'yf': 'BLDR', 'name': 'Builders FirstSource', 'sector': 'Industrials'},
    {'yf': 'BG', 'name': 'Bunge Global', 'sector': 'Consumer Staples'},
    {'yf': 'BXP', 'name': 'BXP, Inc.', 'sector': 'Real Estate'},
    {'yf': 'CHRW', 'name': 'C.H. Robinson', 'sector': 'Industrials'},
    {'yf': 'CDNS', 'name': 'Cadence Design Systems', 'sector': 'Information Technology'},
    {'yf': 'CPT', 'name': 'Camden Property Trust', 'sector': 'Real Estate'},
    {'yf': 'COF', 'name': 'Capital One', 'sector': 'Financials'},
    {'yf': 'CAH', 'name': 'Cardinal Health', 'sector': 'Health Care'},
    {'yf': 'CCL', 'name': 'Carnival Corporation', 'sector': 'Consumer Discretionary'},
    {'yf': 'CARR', 'name': 'Carrier Global', 'sector': 'Industrials'},
    {'yf': 'CVNA', 'name': 'Carvana', 'sector': 'Consumer Discretionary'},
    {'yf': 'CASY', 'name': "Casey's", 'sector': 'Consumer Staples'},
    {'yf': 'CAT', 'name': 'Caterpillar Inc.', 'sector': 'Industrials'},
    {'yf': 'CBOE', 'name': 'Cboe Global Markets', 'sector': 'Financials'},
    {'yf': 'CBRE', 'name': 'CBRE Group', 'sector': 'Real Estate'},
    {'yf': 'CDW', 'name': 'CDW Corporation', 'sector': 'Information Technology'},
    {'yf': 'COR', 'name': 'Cencora', 'sector': 'Health Care'},
    {'yf': 'CNC', 'name': 'Centene Corporation', 'sector': 'Health Care'},
    {'yf': 'CNP', 'name': 'CenterPoint Energy', 'sector': 'Utilities'},
    {'yf': 'CF', 'name': 'CF Industries', 'sector': 'Materials'},
    {'yf': 'CRL', 'name': 'Charles River Laboratories', 'sector': 'Health Care'},
    {'yf': 'SCHW', 'name': 'Charles Schwab Corporation', 'sector': 'Financials'},
    {'yf': 'CHTR', 'name': 'Charter Communications', 'sector': 'Communication Services'},
    {'yf': 'CVX', 'name': 'Chevron Corporation', 'sector': 'Energy'},
    {'yf': 'CMG', 'name': 'Chipotle Mexican Grill', 'sector': 'Consumer Discretionary'},
    {'yf': 'CB', 'name': 'Chubb Limited', 'sector': 'Financials'},
    {'yf': 'CHD', 'name': 'Church & Dwight', 'sector': 'Consumer Staples'},
    {'yf': 'CIEN', 'name': 'Ciena', 'sector': 'Information Technology'},
    {'yf': 'CI', 'name': 'Cigna', 'sector': 'Health Care'},
    {'yf': 'CINF', 'name': 'Cincinnati Financial', 'sector': 'Financials'},
    {'yf': 'CTAS', 'name': 'Cintas', 'sector': 'Industrials'},
    {'yf': 'CSCO', 'name': 'Cisco', 'sector': 'Information Technology'},
    {'yf': 'C', 'name': 'Citigroup', 'sector': 'Financials'},
    {'yf': 'CFG', 'name': 'Citizens Financial Group', 'sector': 'Financials'},
    {'yf': 'CLX', 'name': 'Clorox', 'sector': 'Consumer Staples'},
    {'yf': 'CME', 'name': 'CME Group', 'sector': 'Financials'},
    {'yf': 'CMS', 'name': 'CMS Energy', 'sector': 'Utilities'},
    {'yf': 'KO', 'name': 'Coca-Cola Company (The)', 'sector': 'Consumer Staples'},
    {'yf': 'CTSH', 'name': 'Cognizant', 'sector': 'Information Technology'},
    {'yf': 'COHR', 'name': 'Coherent Corp.', 'sector': 'Information Technology'},
    {'yf': 'COIN', 'name': 'Coinbase', 'sector': 'Financials'},
    {'yf': 'CL', 'name': 'Colgate-Palmolive', 'sector': 'Consumer Staples'},
    {'yf': 'CMCSA', 'name': 'Comcast', 'sector': 'Communication Services'},
    {'yf': 'FIX', 'name': 'Comfort Systems USA', 'sector': 'Industrials'},
    {'yf': 'CAG', 'name': 'Conagra Brands', 'sector': 'Consumer Staples'},
    {'yf': 'COP', 'name': 'ConocoPhillips', 'sector': 'Energy'},
    {'yf': 'ED', 'name': 'Consolidated Edison', 'sector': 'Utilities'},
    {'yf': 'STZ', 'name': 'Constellation Brands', 'sector': 'Consumer Staples'},
    {'yf': 'CEG', 'name': 'Constellation Energy', 'sector': 'Utilities'},
    {'yf': 'COO', 'name': 'Cooper Companies (The)', 'sector': 'Health Care'},
    {'yf': 'CPRT', 'name': 'Copart', 'sector': 'Industrials'},
    {'yf': 'GLW', 'name': 'Corning Inc.', 'sector': 'Information Technology'},
    {'yf': 'CPAY', 'name': 'Corpay', 'sector': 'Financials'},
    {'yf': 'CTVA', 'name': 'Corteva', 'sector': 'Materials'},
    {'yf': 'CSGP', 'name': 'CoStar Group', 'sector': 'Real Estate'},
    {'yf': 'COST', 'name': 'Costco', 'sector': 'Consumer Staples'},
    {'yf': 'CRH', 'name': 'CRH plc', 'sector': 'Materials'},
    {'yf': 'CRWD', 'name': 'CrowdStrike', 'sector': 'Information Technology'},
    {'yf': 'CCI', 'name': 'Crown Castle', 'sector': 'Real Estate'},
    {'yf': 'CSX', 'name': 'CSX Corporation', 'sector': 'Industrials'},
    {'yf': 'CMI', 'name': 'Cummins', 'sector': 'Industrials'},
    {'yf': 'CVS', 'name': 'CVS Health', 'sector': 'Health Care'},
    {'yf': 'DHR', 'name': 'Danaher Corporation', 'sector': 'Health Care'},
    {'yf': 'DRI', 'name': 'Darden Restaurants', 'sector': 'Consumer Discretionary'},
    {'yf': 'DDOG', 'name': 'Datadog', 'sector': 'Information Technology'},
    {'yf': 'DVA', 'name': 'DaVita', 'sector': 'Health Care'},
    {'yf': 'DECK', 'name': 'Deckers Brands', 'sector': 'Consumer Discretionary'},
    {'yf': 'DE', 'name': 'Deere & Company', 'sector': 'Industrials'},
    {'yf': 'DELL', 'name': 'Dell Technologies', 'sector': 'Information Technology'},
    {'yf': 'DAL', 'name': 'Delta Air Lines', 'sector': 'Industrials'},
    {'yf': 'DVN', 'name': 'Devon Energy', 'sector': 'Energy'},
    {'yf': 'DXCM', 'name': 'Dexcom', 'sector': 'Health Care'},
    {'yf': 'FANG', 'name': 'Diamondback Energy', 'sector': 'Energy'},
    {'yf': 'DLR', 'name': 'Digital Realty', 'sector': 'Real Estate'},
    {'yf': 'DG', 'name': 'Dollar General', 'sector': 'Consumer Staples'},
    {'yf': 'DLTR', 'name': 'Dollar Tree', 'sector': 'Consumer Staples'},
    {'yf': 'D', 'name': 'Dominion Energy', 'sector': 'Utilities'},
    {'yf': 'DPZ', 'name': "Domino's", 'sector': 'Consumer Discretionary'},
    {'yf': 'DASH', 'name': 'DoorDash', 'sector': 'Consumer Discretionary'},
    {'yf': 'DOV', 'name': 'Dover Corporation', 'sector': 'Industrials'},
    {'yf': 'DOW', 'name': 'Dow Inc.', 'sector': 'Materials'},
    {'yf': 'DHI', 'name': 'D. R. Horton', 'sector': 'Consumer Discretionary'},
    {'yf': 'DTE', 'name': 'DTE Energy', 'sector': 'Utilities'},
    {'yf': 'DUK', 'name': 'Duke Energy', 'sector': 'Utilities'},
    {'yf': 'DD', 'name': 'DuPont', 'sector': 'Materials'},
    {'yf': 'ETN', 'name': 'Eaton Corporation', 'sector': 'Industrials'},
    {'yf': 'EBAY', 'name': 'eBay Inc.', 'sector': 'Consumer Discretionary'},
    {'yf': 'ECHO', 'name': 'EchoStar', 'sector': 'Communication Services'},
    {'yf': 'ECL', 'name': 'Ecolab', 'sector': 'Materials'},
    {'yf': 'EIX', 'name': 'Edison International', 'sector': 'Utilities'},
    {'yf': 'EW', 'name': 'Edwards Lifesciences', 'sector': 'Health Care'},
    {'yf': 'EA', 'name': 'Electronic Arts', 'sector': 'Communication Services'},
    {'yf': 'ELV', 'name': 'Elevance Health', 'sector': 'Health Care'},
    {'yf': 'EME', 'name': 'Emcor', 'sector': 'Industrials'},
    {'yf': 'EMR', 'name': 'Emerson Electric', 'sector': 'Industrials'},
    {'yf': 'ETR', 'name': 'Entergy', 'sector': 'Utilities'},
    {'yf': 'EOG', 'name': 'EOG Resources', 'sector': 'Energy'},
    {'yf': 'EQT', 'name': 'EQT Corporation', 'sector': 'Energy'},
    {'yf': 'EFX', 'name': 'Equifax', 'sector': 'Industrials'},
    {'yf': 'EQIX', 'name': 'Equinix', 'sector': 'Real Estate'},
    {'yf': 'EQR', 'name': 'Equity Residential', 'sector': 'Real Estate'},
    {'yf': 'ERIE', 'name': 'Erie Indemnity', 'sector': 'Financials'},
    {'yf': 'ESS', 'name': 'Essex Property Trust', 'sector': 'Real Estate'},
    {'yf': 'EL', 'name': 'Estée Lauder Companies (The)', 'sector': 'Consumer Staples'},
    {'yf': 'EG', 'name': 'Everest Group', 'sector': 'Financials'},
    {'yf': 'EVRG', 'name': 'Evergy', 'sector': 'Utilities'},
    {'yf': 'ES', 'name': 'Eversource Energy', 'sector': 'Utilities'},
    {'yf': 'EXC', 'name': 'Exelon', 'sector': 'Utilities'},
    {'yf': 'EXE', 'name': 'Expand Energy', 'sector': 'Energy'},
    {'yf': 'EXPE', 'name': 'Expedia Group', 'sector': 'Consumer Discretionary'},
    {'yf': 'EXPD', 'name': 'Expeditors International', 'sector': 'Industrials'},
    {'yf': 'EXR', 'name': 'Extra Space Storage', 'sector': 'Real Estate'},
    {'yf': 'XOM', 'name': 'ExxonMobil', 'sector': 'Energy'},
    {'yf': 'FFIV', 'name': 'F5, Inc.', 'sector': 'Information Technology'},
    {'yf': 'FDS', 'name': 'FactSet', 'sector': 'Financials'},
    {'yf': 'FICO', 'name': 'Fair Isaac', 'sector': 'Information Technology'},
    {'yf': 'FAST', 'name': 'Fastenal', 'sector': 'Industrials'},
    {'yf': 'FRT', 'name': 'Federal Realty Investment Trust', 'sector': 'Real Estate'},
    {'yf': 'FDX', 'name': 'FedEx', 'sector': 'Industrials'},
    {'yf': 'FDXF', 'name': 'FedEx Freight', 'sector': 'Industrials'},
    {'yf': 'FIS', 'name': 'Fidelity National Information Services', 'sector': 'Financials'},
    {'yf': 'FITB', 'name': 'Fifth Third Bancorp', 'sector': 'Financials'},
    {'yf': 'FSLR', 'name': 'First Solar', 'sector': 'Information Technology'},
    {'yf': 'FE', 'name': 'FirstEnergy', 'sector': 'Utilities'},
    {'yf': 'FISV', 'name': 'Fiserv', 'sector': 'Financials'},
    {'yf': 'FLEX', 'name': 'Flex Ltd.', 'sector': 'Information Technology'},
    {'yf': 'F', 'name': 'Ford Motor Company', 'sector': 'Consumer Discretionary'},
    {'yf': 'FTNT', 'name': 'Fortinet', 'sector': 'Information Technology'},
    {'yf': 'FTV', 'name': 'Fortive', 'sector': 'Industrials'},
    {'yf': 'FOXA', 'name': 'Fox Corporation (Class A)', 'sector': 'Communication Services'},
    {'yf': 'FOX', 'name': 'Fox Corporation (Class B)', 'sector': 'Communication Services'},
    {'yf': 'BEN', 'name': 'Franklin Resources', 'sector': 'Financials'},
    {'yf': 'FCX', 'name': 'Freeport-McMoRan', 'sector': 'Materials'},
    {'yf': 'GRMN', 'name': 'Garmin', 'sector': 'Consumer Discretionary'},
    {'yf': 'IT', 'name': 'Gartner', 'sector': 'Information Technology'},
    {'yf': 'GE', 'name': 'GE Aerospace', 'sector': 'Industrials'},
    {'yf': 'GEHC', 'name': 'GE HealthCare', 'sector': 'Health Care'},
    {'yf': 'GEV', 'name': 'GE Vernova', 'sector': 'Industrials'},
    {'yf': 'GEN', 'name': 'Gen Digital', 'sector': 'Information Technology'},
    {'yf': 'GNRC', 'name': 'Generac', 'sector': 'Industrials'},
    {'yf': 'GD', 'name': 'General Dynamics', 'sector': 'Industrials'},
    {'yf': 'GIS', 'name': 'General Mills', 'sector': 'Consumer Staples'},
    {'yf': 'GM', 'name': 'General Motors', 'sector': 'Consumer Discretionary'},
    {'yf': 'GPC', 'name': 'Genuine Parts Company', 'sector': 'Consumer Discretionary'},
    {'yf': 'GILD', 'name': 'Gilead Sciences', 'sector': 'Health Care'},
    {'yf': 'GPN', 'name': 'Global Payments', 'sector': 'Financials'},
    {'yf': 'GL', 'name': 'Globe Life', 'sector': 'Financials'},
    {'yf': 'GDDY', 'name': 'GoDaddy', 'sector': 'Information Technology'},
    {'yf': 'GS', 'name': 'Goldman Sachs', 'sector': 'Financials'},
    {'yf': 'HAL', 'name': 'Halliburton', 'sector': 'Energy'},
    {'yf': 'HIG', 'name': 'Hartford (The)', 'sector': 'Financials'},
    {'yf': 'HAS', 'name': 'Hasbro', 'sector': 'Consumer Discretionary'},
    {'yf': 'HCA', 'name': 'HCA Healthcare', 'sector': 'Health Care'},
    {'yf': 'DOC', 'name': 'Healthpeak Properties', 'sector': 'Real Estate'},
    {'yf': 'HSIC', 'name': 'Henry Schein', 'sector': 'Health Care'},
    {'yf': 'HSY', 'name': 'Hershey Company (The)', 'sector': 'Consumer Staples'},
    {'yf': 'HPE', 'name': 'Hewlett Packard Enterprise', 'sector': 'Information Technology'},
    {'yf': 'HLT', 'name': 'Hilton Worldwide', 'sector': 'Consumer Discretionary'},
    {'yf': 'HD', 'name': 'Home Depot (The)', 'sector': 'Consumer Discretionary'},
    {'yf': 'HON', 'name': 'Honeywell', 'sector': 'Industrials'},
    {'yf': 'HRL', 'name': 'Hormel Foods', 'sector': 'Consumer Staples'},
    {'yf': 'HST', 'name': 'Host Hotels & Resorts', 'sector': 'Real Estate'},
    {'yf': 'HWM', 'name': 'Howmet Aerospace', 'sector': 'Industrials'},
    {'yf': 'HPQ', 'name': 'HP Inc.', 'sector': 'Information Technology'},
    {'yf': 'HUBB', 'name': 'Hubbell Incorporated', 'sector': 'Industrials'},
    {'yf': 'HUM', 'name': 'Humana', 'sector': 'Health Care'},
    {'yf': 'HBAN', 'name': 'Huntington Bancshares', 'sector': 'Financials'},
    {'yf': 'HII', 'name': 'Huntington Ingalls Industries', 'sector': 'Industrials'},
    {'yf': 'IBM', 'name': 'IBM', 'sector': 'Information Technology'},
    {'yf': 'IEX', 'name': 'IDEX Corporation', 'sector': 'Industrials'},
    {'yf': 'IDXX', 'name': 'Idexx Laboratories', 'sector': 'Health Care'},
    {'yf': 'ITW', 'name': 'Illinois Tool Works', 'sector': 'Industrials'},
    {'yf': 'INCY', 'name': 'Incyte', 'sector': 'Health Care'},
    {'yf': 'IR', 'name': 'Ingersoll Rand', 'sector': 'Industrials'},
    {'yf': 'PODD', 'name': 'Insulet Corporation', 'sector': 'Health Care'},
    {'yf': 'INTC', 'name': 'Intel', 'sector': 'Information Technology'},
    {'yf': 'IBKR', 'name': 'Interactive Brokers', 'sector': 'Financials'},
    {'yf': 'ICE', 'name': 'Intercontinental Exchange', 'sector': 'Financials'},
    {'yf': 'IFF', 'name': 'International Flavors & Fragrances', 'sector': 'Materials'},
    {'yf': 'IP', 'name': 'International Paper', 'sector': 'Materials'},
    {'yf': 'INTU', 'name': 'Intuit', 'sector': 'Information Technology'},
    {'yf': 'ISRG', 'name': 'Intuitive Surgical', 'sector': 'Health Care'},
    {'yf': 'IVZ', 'name': 'Invesco', 'sector': 'Financials'},
    {'yf': 'INVH', 'name': 'Invitation Homes', 'sector': 'Real Estate'},
    {'yf': 'IQV', 'name': 'IQVIA', 'sector': 'Health Care'},
    {'yf': 'IRM', 'name': 'Iron Mountain', 'sector': 'Real Estate'},
    {'yf': 'JBHT', 'name': 'J.B. Hunt', 'sector': 'Industrials'},
    {'yf': 'JBL', 'name': 'Jabil', 'sector': 'Information Technology'},
    {'yf': 'JKHY', 'name': 'Jack Henry & Associates', 'sector': 'Financials'},
    {'yf': 'J', 'name': 'Jacobs Solutions', 'sector': 'Industrials'},
    {'yf': 'JNJ', 'name': 'Johnson & Johnson', 'sector': 'Health Care'},
    {'yf': 'JCI', 'name': 'Johnson Controls', 'sector': 'Industrials'},
    {'yf': 'JPM', 'name': 'JPMorgan Chase', 'sector': 'Financials'},
    {'yf': 'KVUE', 'name': 'Kenvue', 'sector': 'Consumer Staples'},
    {'yf': 'KDP', 'name': 'Keurig Dr Pepper', 'sector': 'Consumer Staples'},
    {'yf': 'KEY', 'name': 'KeyCorp', 'sector': 'Financials'},
    {'yf': 'KEYS', 'name': 'Keysight Technologies', 'sector': 'Information Technology'},
    {'yf': 'KMB', 'name': 'Kimberly-Clark', 'sector': 'Consumer Staples'},
    {'yf': 'KIM', 'name': 'Kimco Realty', 'sector': 'Real Estate'},
    {'yf': 'KMI', 'name': 'Kinder Morgan', 'sector': 'Energy'},
    {'yf': 'KKR', 'name': 'KKR & Co.', 'sector': 'Financials'},
    {'yf': 'KLAC', 'name': 'KLA Corporation', 'sector': 'Information Technology'},
    {'yf': 'KHC', 'name': 'Kraft Heinz', 'sector': 'Consumer Staples'},
    {'yf': 'KR', 'name': 'Kroger', 'sector': 'Consumer Staples'},
    {'yf': 'LHX', 'name': 'L3Harris', 'sector': 'Industrials'},
    {'yf': 'LH', 'name': 'Labcorp', 'sector': 'Health Care'},
    {'yf': 'LRCX', 'name': 'Lam Research', 'sector': 'Information Technology'},
    {'yf': 'LVS', 'name': 'Las Vegas Sands', 'sector': 'Consumer Discretionary'},
    {'yf': 'LDOS', 'name': 'Leidos', 'sector': 'Industrials'},
    {'yf': 'LEN', 'name': 'Lennar', 'sector': 'Consumer Discretionary'},
    {'yf': 'LII', 'name': 'Lennox International', 'sector': 'Industrials'},
    {'yf': 'LLY', 'name': 'Lilly (Eli)', 'sector': 'Health Care'},
    {'yf': 'LIN', 'name': 'Linde plc', 'sector': 'Materials'},
    {'yf': 'LYV', 'name': 'Live Nation Entertainment', 'sector': 'Communication Services'},
    {'yf': 'LMT', 'name': 'Lockheed Martin', 'sector': 'Industrials'},
    {'yf': 'L', 'name': 'Loews Corporation', 'sector': 'Financials'},
    {'yf': 'LOW', 'name': "Lowe's", 'sector': 'Consumer Discretionary'},
    {'yf': 'LULU', 'name': 'Lululemon Athletica', 'sector': 'Consumer Discretionary'},
    {'yf': 'LITE', 'name': 'Lumentum', 'sector': 'Information Technology'},
    {'yf': 'LYB', 'name': 'LyondellBasell', 'sector': 'Materials'},
    {'yf': 'MTB', 'name': 'M&T Bank', 'sector': 'Financials'},
    {'yf': 'MPC', 'name': 'Marathon Petroleum', 'sector': 'Energy'},
    {'yf': 'MAR', 'name': 'Marriott International', 'sector': 'Consumer Discretionary'},
    {'yf': 'MRSH', 'name': 'Marsh McLennan', 'sector': 'Financials'},
    {'yf': 'MLM', 'name': 'Martin Marietta Materials', 'sector': 'Materials'},
    {'yf': 'MRVL', 'name': 'Marvell Technology', 'sector': 'Information Technology'},
    {'yf': 'MAS', 'name': 'Masco', 'sector': 'Industrials'},
    {'yf': 'MA', 'name': 'Mastercard', 'sector': 'Financials'},
    {'yf': 'MKC', 'name': 'McCormick & Company', 'sector': 'Consumer Staples'},
    {'yf': 'MCD', 'name': "McDonald's", 'sector': 'Consumer Discretionary'},
    {'yf': 'MCK', 'name': 'McKesson Corporation', 'sector': 'Health Care'},
    {'yf': 'MDT', 'name': 'Medtronic', 'sector': 'Health Care'},
    {'yf': 'MRK', 'name': 'Merck & Co.', 'sector': 'Health Care'},
    {'yf': 'META', 'name': 'Meta Platforms', 'sector': 'Communication Services'},
    {'yf': 'MET', 'name': 'MetLife', 'sector': 'Financials'},
    {'yf': 'MTD', 'name': 'Mettler Toledo', 'sector': 'Health Care'},
    {'yf': 'MGM', 'name': 'MGM Resorts', 'sector': 'Consumer Discretionary'},
    {'yf': 'MCHP', 'name': 'Microchip Technology', 'sector': 'Information Technology'},
    {'yf': 'MU', 'name': 'Micron Technology', 'sector': 'Information Technology'},
    {'yf': 'MSFT', 'name': 'Microsoft', 'sector': 'Information Technology'},
    {'yf': 'MAA', 'name': 'Mid-America Apartment Communities', 'sector': 'Real Estate'},
    {'yf': 'MRNA', 'name': 'Moderna', 'sector': 'Health Care'},
    {'yf': 'TAP', 'name': 'Molson Coors Beverage Company', 'sector': 'Consumer Staples'},
    {'yf': 'MDLZ', 'name': 'Mondelez International', 'sector': 'Consumer Staples'},
    {'yf': 'MPWR', 'name': 'Monolithic Power Systems', 'sector': 'Information Technology'},
    {'yf': 'MNST', 'name': 'Monster Beverage', 'sector': 'Consumer Staples'},
    {'yf': 'MCO', 'name': "Moody's Corporation", 'sector': 'Financials'},
    {'yf': 'MS', 'name': 'Morgan Stanley', 'sector': 'Financials'},
    {'yf': 'MOS', 'name': 'Mosaic Company (The)', 'sector': 'Materials'},
    {'yf': 'MSI', 'name': 'Motorola Solutions', 'sector': 'Information Technology'},
    {'yf': 'MSCI', 'name': 'MSCI Inc.', 'sector': 'Financials'},
    {'yf': 'NDAQ', 'name': 'Nasdaq, Inc.', 'sector': 'Financials'},
    {'yf': 'NTAP', 'name': 'NetApp', 'sector': 'Information Technology'},
    {'yf': 'NFLX', 'name': 'Netflix', 'sector': 'Communication Services'},
    {'yf': 'NEM', 'name': 'Newmont', 'sector': 'Materials'},
    {'yf': 'NWSA', 'name': 'News Corp (Class A)', 'sector': 'Communication Services'},
    {'yf': 'NWS', 'name': 'News Corp (Class B)', 'sector': 'Communication Services'},
    {'yf': 'NEE', 'name': 'NextEra Energy', 'sector': 'Utilities'},
    {'yf': 'NKE', 'name': 'Nike, Inc.', 'sector': 'Consumer Discretionary'},
    {'yf': 'NI', 'name': 'NiSource', 'sector': 'Utilities'},
    {'yf': 'NDSN', 'name': 'Nordson Corporation', 'sector': 'Industrials'},
    {'yf': 'NSC', 'name': 'Norfolk Southern', 'sector': 'Industrials'},
    {'yf': 'NTRS', 'name': 'Northern Trust', 'sector': 'Financials'},
    {'yf': 'NOC', 'name': 'Northrop Grumman', 'sector': 'Industrials'},
    {'yf': 'NCLH', 'name': 'Norwegian Cruise Line Holdings', 'sector': 'Consumer Discretionary'},
    {'yf': 'NRG', 'name': 'NRG Energy', 'sector': 'Utilities'},
    {'yf': 'NUE', 'name': 'Nucor', 'sector': 'Materials'},
    {'yf': 'NVDA', 'name': 'Nvidia', 'sector': 'Information Technology'},
    {'yf': 'NVR', 'name': 'NVR, Inc.', 'sector': 'Consumer Discretionary'},
    {'yf': 'NXPI', 'name': 'NXP Semiconductors', 'sector': 'Information Technology'},
    {'yf': 'ORLY', 'name': 'O’Reilly Automotive', 'sector': 'Consumer Discretionary'},
    {'yf': 'OXY', 'name': 'Occidental Petroleum', 'sector': 'Energy'},
    {'yf': 'ODFL', 'name': 'Old Dominion', 'sector': 'Industrials'},
    {'yf': 'OMC', 'name': 'Omnicom Group', 'sector': 'Communication Services'},
    {'yf': 'ON', 'name': 'ON Semiconductor', 'sector': 'Information Technology'},
    {'yf': 'OKE', 'name': 'Oneok', 'sector': 'Energy'},
    {'yf': 'ORCL', 'name': 'Oracle Corporation', 'sector': 'Information Technology'},
    {'yf': 'OTIS', 'name': 'Otis Worldwide', 'sector': 'Industrials'},
    {'yf': 'PCAR', 'name': 'Paccar', 'sector': 'Industrials'},
    {'yf': 'PKG', 'name': 'Packaging Corporation of America', 'sector': 'Materials'},
    {'yf': 'PLTR', 'name': 'Palantir Technologies', 'sector': 'Information Technology'},
    {'yf': 'PANW', 'name': 'Palo Alto Networks', 'sector': 'Information Technology'},
    {'yf': 'PSKY', 'name': 'Paramount Skydance Corporation', 'sector': 'Communication Services'},
    {'yf': 'PH', 'name': 'Parker Hannifin', 'sector': 'Industrials'},
    {'yf': 'PAYX', 'name': 'Paychex', 'sector': 'Industrials'},
    {'yf': 'PYPL', 'name': 'PayPal', 'sector': 'Financials'},
    {'yf': 'PNR', 'name': 'Pentair', 'sector': 'Industrials'},
    {'yf': 'PEP', 'name': 'PepsiCo', 'sector': 'Consumer Staples'},
    {'yf': 'PFE', 'name': 'Pfizer', 'sector': 'Health Care'},
    {'yf': 'PCG', 'name': 'PG&E Corporation', 'sector': 'Utilities'},
    {'yf': 'PM', 'name': 'Philip Morris International', 'sector': 'Consumer Staples'},
    {'yf': 'PSX', 'name': 'Phillips 66', 'sector': 'Energy'},
    {'yf': 'PNW', 'name': 'Pinnacle West Capital', 'sector': 'Utilities'},
    {'yf': 'PNC', 'name': 'PNC Financial Services', 'sector': 'Financials'},
    {'yf': 'PPG', 'name': 'PPG Industries', 'sector': 'Materials'},
    {'yf': 'PPL', 'name': 'PPL Corporation', 'sector': 'Utilities'},
    {'yf': 'PFG', 'name': 'Principal Financial Group', 'sector': 'Financials'},
    {'yf': 'PG', 'name': 'Procter & Gamble', 'sector': 'Consumer Staples'},
    {'yf': 'PGR', 'name': 'Progressive Corporation', 'sector': 'Financials'},
    {'yf': 'PLD', 'name': 'Prologis', 'sector': 'Real Estate'},
    {'yf': 'PRU', 'name': 'Prudential Financial', 'sector': 'Financials'},
    {'yf': 'PEG', 'name': 'Public Service Enterprise Group', 'sector': 'Utilities'},
    {'yf': 'PTC', 'name': 'PTC Inc.', 'sector': 'Information Technology'},
    {'yf': 'PSA', 'name': 'Public Storage', 'sector': 'Real Estate'},
    {'yf': 'PHM', 'name': 'PulteGroup', 'sector': 'Consumer Discretionary'},
    {'yf': 'PWR', 'name': 'Quanta Services', 'sector': 'Industrials'},
    {'yf': 'QCOM', 'name': 'Qualcomm', 'sector': 'Information Technology'},
    {'yf': 'DGX', 'name': 'Quest Diagnostics', 'sector': 'Health Care'},
    {'yf': 'Q', 'name': 'Qnity Electronics', 'sector': 'Information Technology'},
    {'yf': 'RL', 'name': 'Ralph Lauren Corporation', 'sector': 'Consumer Discretionary'},
    {'yf': 'RJF', 'name': 'Raymond James Financial', 'sector': 'Financials'},
    {'yf': 'RTX', 'name': 'RTX Corporation', 'sector': 'Industrials'},
    {'yf': 'O', 'name': 'Realty Income', 'sector': 'Real Estate'},
    {'yf': 'REG', 'name': 'Regency Centers', 'sector': 'Real Estate'},
    {'yf': 'REGN', 'name': 'Regeneron Pharmaceuticals', 'sector': 'Health Care'},
    {'yf': 'RF', 'name': 'Regions Financial Corporation', 'sector': 'Financials'},
    {'yf': 'RSG', 'name': 'Republic Services', 'sector': 'Industrials'},
    {'yf': 'RMD', 'name': 'ResMed', 'sector': 'Health Care'},
    {'yf': 'RVTY', 'name': 'Revvity', 'sector': 'Health Care'},
    {'yf': 'HOOD', 'name': 'Robinhood Markets', 'sector': 'Financials'},
    {'yf': 'ROK', 'name': 'Rockwell Automation', 'sector': 'Industrials'},
    {'yf': 'ROL', 'name': 'Rollins, Inc.', 'sector': 'Industrials'},
    {'yf': 'ROP', 'name': 'Roper Technologies', 'sector': 'Information Technology'},
    {'yf': 'ROST', 'name': 'Ross Stores', 'sector': 'Consumer Discretionary'},
    {'yf': 'RCL', 'name': 'Royal Caribbean Group', 'sector': 'Consumer Discretionary'},
    {'yf': 'SPGI', 'name': 'S&P Global', 'sector': 'Financials'},
    {'yf': 'CRM', 'name': 'Salesforce', 'sector': 'Information Technology'},
    {'yf': 'SNDK', 'name': 'Sandisk', 'sector': 'Information Technology'},
    {'yf': 'SBAC', 'name': 'SBA Communications', 'sector': 'Real Estate'},
    {'yf': 'SLB', 'name': 'Schlumberger', 'sector': 'Energy'},
    {'yf': 'STX', 'name': 'Seagate Technology', 'sector': 'Information Technology'},
    {'yf': 'SRE', 'name': 'Sempra', 'sector': 'Utilities'},
    {'yf': 'NOW', 'name': 'ServiceNow', 'sector': 'Information Technology'},
    {'yf': 'SHW', 'name': 'Sherwin-Williams', 'sector': 'Materials'},
    {'yf': 'SPG', 'name': 'Simon Property Group', 'sector': 'Real Estate'},
    {'yf': 'SWKS', 'name': 'Skyworks Solutions', 'sector': 'Information Technology'},
    {'yf': 'SJM', 'name': 'J.M. Smucker Company (The)', 'sector': 'Consumer Staples'},
    {'yf': 'SW', 'name': 'Smurfit Westrock', 'sector': 'Materials'},
    {'yf': 'SNA', 'name': 'Snap-on', 'sector': 'Industrials'},
    {'yf': 'SOLV', 'name': 'Solventum', 'sector': 'Health Care'},
    {'yf': 'SO', 'name': 'Southern Company', 'sector': 'Utilities'},
    {'yf': 'LUV', 'name': 'Southwest Airlines', 'sector': 'Industrials'},
    {'yf': 'SWK', 'name': 'Stanley Black & Decker', 'sector': 'Industrials'},
    {'yf': 'SBUX', 'name': 'Starbucks', 'sector': 'Consumer Discretionary'},
    {'yf': 'STT', 'name': 'State Street Corporation', 'sector': 'Financials'},
    {'yf': 'STLD', 'name': 'Steel Dynamics', 'sector': 'Materials'},
    {'yf': 'STE', 'name': 'Steris', 'sector': 'Health Care'},
    {'yf': 'SYK', 'name': 'Stryker Corporation', 'sector': 'Health Care'},
    {'yf': 'SMCI', 'name': 'Supermicro', 'sector': 'Information Technology'},
    {'yf': 'SYF', 'name': 'Synchrony Financial', 'sector': 'Financials'},
    {'yf': 'SNPS', 'name': 'Synopsys', 'sector': 'Information Technology'},
    {'yf': 'SYY', 'name': 'Sysco', 'sector': 'Consumer Staples'},
    {'yf': 'TMUS', 'name': 'T-Mobile US', 'sector': 'Communication Services'},
    {'yf': 'TROW', 'name': 'T. Rowe Price', 'sector': 'Financials'},
    {'yf': 'TTWO', 'name': 'Take-Two Interactive', 'sector': 'Communication Services'},
    {'yf': 'TPR', 'name': 'Tapestry, Inc.', 'sector': 'Consumer Discretionary'},
    {'yf': 'TRGP', 'name': 'Targa Resources', 'sector': 'Energy'},
    {'yf': 'TGT', 'name': 'Target Corporation', 'sector': 'Consumer Staples'},
    {'yf': 'TEL', 'name': 'TE Connectivity', 'sector': 'Information Technology'},
    {'yf': 'TDY', 'name': 'Teledyne Technologies', 'sector': 'Information Technology'},
    {'yf': 'TER', 'name': 'Teradyne', 'sector': 'Information Technology'},
    {'yf': 'TSLA', 'name': 'Tesla, Inc.', 'sector': 'Consumer Discretionary'},
    {'yf': 'TXN', 'name': 'Texas Instruments', 'sector': 'Information Technology'},
    {'yf': 'TPL', 'name': 'Texas Pacific Land Corporation', 'sector': 'Energy'},
    {'yf': 'TXT', 'name': 'Textron', 'sector': 'Industrials'},
    {'yf': 'TMO', 'name': 'Thermo Fisher Scientific', 'sector': 'Health Care'},
    {'yf': 'TJX', 'name': 'TJX Companies', 'sector': 'Consumer Discretionary'},
    {'yf': 'TKO', 'name': 'TKO Group Holdings', 'sector': 'Communication Services'},
    {'yf': 'TTD', 'name': 'Trade Desk (The)', 'sector': 'Communication Services'},
    {'yf': 'TSCO', 'name': 'Tractor Supply', 'sector': 'Consumer Discretionary'},
    {'yf': 'TT', 'name': 'Trane Technologies', 'sector': 'Industrials'},
    {'yf': 'TDG', 'name': 'TransDigm Group', 'sector': 'Industrials'},
    {'yf': 'TRV', 'name': 'Travelers Companies (The)', 'sector': 'Financials'},
    {'yf': 'TRMB', 'name': 'Trimble Inc.', 'sector': 'Information Technology'},
    {'yf': 'TFC', 'name': 'Truist Financial', 'sector': 'Financials'},
    {'yf': 'TYL', 'name': 'Tyler Technologies', 'sector': 'Information Technology'},
    {'yf': 'TSN', 'name': 'Tyson Foods', 'sector': 'Consumer Staples'},
    {'yf': 'USB', 'name': 'U.S. Bancorp', 'sector': 'Financials'},
    {'yf': 'UBER', 'name': 'Uber', 'sector': 'Industrials'},
    {'yf': 'UDR', 'name': 'UDR, Inc.', 'sector': 'Real Estate'},
    {'yf': 'ULTA', 'name': 'Ulta Beauty', 'sector': 'Consumer Discretionary'},
    {'yf': 'UNP', 'name': 'Union Pacific Corporation', 'sector': 'Industrials'},
    {'yf': 'UAL', 'name': 'United Airlines Holdings', 'sector': 'Industrials'},
    {'yf': 'UPS', 'name': 'United Parcel Service', 'sector': 'Industrials'},
    {'yf': 'URI', 'name': 'United Rentals', 'sector': 'Industrials'},
    {'yf': 'UNH', 'name': 'UnitedHealth Group', 'sector': 'Health Care'},
    {'yf': 'UHS', 'name': 'Universal Health Services', 'sector': 'Health Care'},
    {'yf': 'VLO', 'name': 'Valero Energy', 'sector': 'Energy'},
    {'yf': 'VEEV', 'name': 'Veeva Systems', 'sector': 'Health Care'},
    {'yf': 'VTR', 'name': 'Ventas', 'sector': 'Real Estate'},
    {'yf': 'VLTO', 'name': 'Veralto', 'sector': 'Industrials'},
    {'yf': 'VRSN', 'name': 'Verisign', 'sector': 'Information Technology'},
    {'yf': 'VRSK', 'name': 'Verisk Analytics', 'sector': 'Industrials'},
    {'yf': 'VZ', 'name': 'Verizon', 'sector': 'Communication Services'},
    {'yf': 'VRTX', 'name': 'Vertex Pharmaceuticals', 'sector': 'Health Care'},
    {'yf': 'VRT', 'name': 'Vertiv', 'sector': 'Industrials'},
    {'yf': 'VTRS', 'name': 'Viatris', 'sector': 'Health Care'},
    {'yf': 'VICI', 'name': 'Vici Properties', 'sector': 'Real Estate'},
    {'yf': 'V', 'name': 'Visa Inc.', 'sector': 'Financials'},
    {'yf': 'VST', 'name': 'Vistra Corp.', 'sector': 'Utilities'},
    {'yf': 'VMC', 'name': 'Vulcan Materials Company', 'sector': 'Materials'},
    {'yf': 'WRB', 'name': 'W. R. Berkley Corporation', 'sector': 'Financials'},
    {'yf': 'GWW', 'name': 'W. W. Grainger', 'sector': 'Industrials'},
    {'yf': 'WAB', 'name': 'Wabtec', 'sector': 'Industrials'},
    {'yf': 'WMT', 'name': 'Walmart', 'sector': 'Consumer Staples'},
    {'yf': 'DIS', 'name': 'Walt Disney Company (The)', 'sector': 'Communication Services'},
    {'yf': 'WBD', 'name': 'Warner Bros. Discovery', 'sector': 'Communication Services'},
    {'yf': 'WM', 'name': 'Waste Management', 'sector': 'Industrials'},
    {'yf': 'WAT', 'name': 'Waters Corporation', 'sector': 'Health Care'},
    {'yf': 'WEC', 'name': 'WEC Energy Group', 'sector': 'Utilities'},
    {'yf': 'WFC', 'name': 'Wells Fargo', 'sector': 'Financials'},
    {'yf': 'WELL', 'name': 'Welltower', 'sector': 'Real Estate'},
    {'yf': 'WST', 'name': 'West Pharmaceutical Services', 'sector': 'Health Care'},
    {'yf': 'WDC', 'name': 'Western Digital', 'sector': 'Information Technology'},
    {'yf': 'WY', 'name': 'Weyerhaeuser', 'sector': 'Real Estate'},
    {'yf': 'WSM', 'name': 'Williams-Sonoma, Inc.', 'sector': 'Consumer Discretionary'},
    {'yf': 'WMB', 'name': 'Williams Companies', 'sector': 'Energy'},
    {'yf': 'WTW', 'name': 'Willis Towers Watson', 'sector': 'Financials'},
    {'yf': 'WDAY', 'name': 'Workday, Inc.', 'sector': 'Information Technology'},
    {'yf': 'WYNN', 'name': 'Wynn Resorts', 'sector': 'Consumer Discretionary'},
    {'yf': 'XEL', 'name': 'Xcel Energy', 'sector': 'Utilities'},
    {'yf': 'XYL', 'name': 'Xylem Inc.', 'sector': 'Industrials'},
    {'yf': 'YUM', 'name': 'Yum! Brands', 'sector': 'Consumer Discretionary'},
    {'yf': 'ZBRA', 'name': 'Zebra Technologies', 'sector': 'Information Technology'},
    {'yf': 'ZBH', 'name': 'Zimmer Biomet', 'sector': 'Health Care'},
    {'yf': 'ZTS', 'name': 'Zoetis', 'sector': 'Health Care'},
]

STOCKS = [(s['yf'], s['name']) for s in SP500]
YF_TO_NAME = {s['yf']: s['name'] for s in SP500}
YF_TO_SECTOR = {s['yf']: s['sector'] for s in SP500}

if __name__ == '__main__':
    syms = [s['yf'] for s in SP500]
    assert 450 <= len(SP500) <= 520, 'SP500 count out of range: %d' % len(SP500)
    assert all(syms), 'empty yf symbol present'
    assert len(set(syms)) == len(syms), 'duplicate yf symbol present'
    print('SP500 tickers:', len(SP500))
